# Generated by Django 5.1.5 on 2025-09-28 20:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('BAILLEUR', 'Bailleur'), ('CLIENT', 'Client')], max_length=20)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('adresse', models.TextField(blank=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'utilisateur',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rue', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('pays', models.CharField(default='France', max_length=100)),
                ('complement', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'adresse',
            },
        ),
        migrations.CreateModel(
            name='ContratBail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('type_contrat', models.CharField(choices=[('HABITATION', 'Habitation'), ('COMMERCIAL', 'Commercial')], max_length=20)),
                ('loyer_mensuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('caution', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition_particulieres', models.TextField(blank=True)),
                ('date_signature', models.DateTimeField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'contrat_bail',
            },
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'administrateur',
            },
            bases=('bd.utilisateur',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bailleur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('numero_siret', models.CharField(blank=True, max_length=14, null=True)),
            ],
            options={
                'db_table': 'bailleur',
            },
            bases=('bd.utilisateur',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('criteres_recherche', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'client',
            },
            bases=('bd.utilisateur',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('RETARD', 'En retard')], default='EN_ATTENTE', max_length=20)),
                ('methode_paiement', models.CharField(choices=[('CARTE', 'Carte bancaire'), ('VIREMENT', 'Virement bancaire'), ('ESPECES', 'Espèces')], default='CARTE', max_length=20)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='bd.contratbail')),
            ],
            options={
                'db_table': 'paiement',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Propriete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('type_propriete', models.CharField(choices=[('APPARTEMENT', 'Appartement'), ('MAISON', 'Maison'), ('COMMERCIAL', 'Local Commercial'), ('TERRAIN', 'Terrain')], max_length=20)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('surface', models.DecimalField(decimal_places=2, max_digits=7)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('LOUE', 'Loué'), ('RESERVE', 'Réservé')], default='DISPONIBLE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietes', to='bd.adresse')),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietes', to='bd.bailleur')),
            ],
            options={
                'db_table': 'propriete',
            },
        ),
        migrations.AddField(
            model_name='contratbail',
            name='propriete',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrat_bail', to='bd.propriete'),
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('interesse', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('PROGRAMMEE', 'Programmée'), ('EFFECTUEE', 'Effectuée'), ('ANNULEE', 'Annulée')], default='PROGRAMMEE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('propriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='bd.propriete')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='bd.client')),
            ],
            options={
                'db_table': 'visite',
                'ordering': ['-date_visite'],
            },
        ),
        migrations.AddField(
            model_name='contratbail',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='bd.client'),
        ),
    ]
